workflows:
  release:
    name: Build Android & iOS Release
    max_build_duration: 60
    environment:
      flutter: 3.29.2
      xcode: latest
      cocoapods: default
      vars:
        MOOSE_GAME_SECRET: $MOOSE_GAME_SECRET
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: production
          include: true
          source: true
    cache:
      cache_paths:
        - ~/.pub-cache
        - ~/.gradle/caches
        - ~/.gradle/wrapper
        - ios/Pods
    scripts:
      # 1. Get outer app dependencies
      - name: Get Flutter packages
        script: flutter pub get

      # 2. Generate code in inner package
      - name: Generate API client
        script: |
          cd lib/api_client
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs
          cd ../..

      # 3. iOS dependencies
      - name: Install CocoaPods
        script: |
          cd ios
          pod install --repo-update
          cd ..

      # 4. Increment build number
      - name: Set build number
        script: |
          # Use Codemagic build number env variable
          flutter pub run flutter_version increment-build-number --build-number $BUILD_NUMBER

      # 5. Build Android AppBundle
      - name: Build Android AppBundle (release)
        script: flutter build appbundle --release --build-number=$BUILD_NUMBER

      # 6. Build Android APK (optional)
      - name: Build Android APK (release)
        script: flutter build apk --release --build-number=$BUILD_NUMBER

      # 7. Build iOS IPA
      - name: Build iOS IPA
        script: flutter build ipa --release --no-codesign --build-number=$BUILD_NUMBER

    artifacts:
      - build/app/outputs/bundle/release/*.aab
      - build/app/outputs/flutter-apk/*.apk
      - build/ios/ipa/*.ipa
      - flutter_drive.log

    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: production
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: false
        release_type: APP_STORE
