import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

class ThemeCubit extends Cubit<ThemeData> {
  ThemeCubit(): super(mat3ThemeLight);

  void setTheme(_theme) {
    emit(_theme);
  }
}

final ThemeData mat3ThemeDark = ThemeData(
  useMaterial3: true,
  colorScheme: ColorScheme.fromSeed(
    seedColor: const Color.fromRGBO(56, 142, 60, 1), // colors.green[700]
    brightness: Brightness.dark,
    onPrimary: Colors.white,
    primary: const Color.fromRGBO(56, 142, 60, 1), // colors.green[700]
    surfaceTint: Color.fromRGBO(3, 51, 6, 1), 
    surface: Color.fromRGBO(34, 34, 34, 1),
    onBackground: Colors.white,
    onSecondary: Colors.white,
    // I just swapped the autogenerated colors for error and onError
    onError: Color(0xffffb4ab),
    error: Color(0xff690005), 
  ),
  // Color used for circular loading indicator in some places
  // Also used in top/bottom bar and the background shape, and in many other places where previous
  // developers used orange to spice things up. Don't blame me if it looks bad.
  primaryColor: const Color.fromRGBO(56, 142, 60, 1), // colors.green[700]
  primaryColorLight: Colors.green[800], // Used for the banner/background on the contact page
  appBarTheme: AppBarTheme(color: Colors.green[700]),
  textTheme: TextTheme(
    displayLarge: const TextStyle(
      fontSize: 72,
      fontWeight: FontWeight.bold,
      fontFamily: 'Helvetica Neue',
      color: Colors.white
    ),
    titleLarge: const TextStyle(
      fontSize: 30,
      fontStyle: FontStyle.normal,
      fontFamily: 'Helvetica Neue',
      color: Colors.white
    ),
    headlineMedium: const TextStyle( // Ex: titles on the event page
      fontSize: 25,
      fontStyle: FontStyle.normal,
      fontFamily: 'Helvetica Neue',
      color: const Color.fromRGBO(56, 142, 60, 1) // colors.green[700]
    ),
    bodyMedium: const TextStyle(
      fontSize: 15,
      fontStyle: FontStyle.normal,
      fontFamily: 'Helvetica Neue'
    ),
    displaySmall: const TextStyle(
      fontSize: 12,
      fontStyle: FontStyle.normal,
      fontFamily: 'Helvetica Neue'
    ),
    labelLarge: const TextStyle(
      fontSize: 16,
      fontWeight: FontWeight.bold,
      fontFamily: 'Helvetica Neue'
    ),
  ),

  textButtonTheme: TextButtonThemeData(
    style: ButtonStyle(
      backgroundColor: MaterialStateProperty.all<Color>(Colors.green[700]!),
      foregroundColor: MaterialStateProperty.all<Color>(Colors.white),
    ),
  ),

  // Used for log in page (among other places?)
  inputDecorationTheme: InputDecorationTheme(
    focusedBorder: UnderlineInputBorder(borderSide: BorderSide(color: Colors.green[700]!)),
    labelStyle: TextStyle(color: Colors.green[700]!),
    hintStyle: TextStyle(color: const Color.fromRGBO(117, 117, 117, 1)), // Colors.grey[600]
  ),
);

final ThemeData mat3ThemeLight = ThemeData(
  /* Since the app is not built around material 3, I've had to be a
  bit creative with the application of some of these colours. */

  useMaterial3: true,
  colorScheme: ColorScheme.fromSeed(
    seedColor: const Color.fromRGBO(245, 124, 0, 1), // colors.orange[700]
    primary: Colors.orange[600], // colors.orange[600], used unsparingly and in random places, I just ported it over
    brightness: Brightness.light,
    // Used, ex. for the background of letters in songbook and as background for other text that 
    // should stand out a bit (like explanations in the account settings)
    surfaceVariant: Colors.grey[200]!, 
    onSurfaceVariant: Colors.black,
    onPrimary: Colors.black,
    // Used, ex. for the background of the cafe shifts/the notification cards
    // this is the wrong way to use this color (it should not have 100% opacity), 
    // so please change it when time allows
    surfaceTint: Colors.orange[100], 
    onInverseSurface: Colors.black, // Used, ex. for the text on the cafe shifts
    // Used as background for cards, like event cards in calendar, notification cards, items on "other" page
    surface: Color.fromRGBO(255, 254, 251, 1), // A color that kinda looked nice
    background: Colors.white, //  Main new background color
    // (only) Used for a selected element in the bottom bar
    onPrimaryContainer: Colors.white,

    error: Colors.red[600], // Same as the old error color

    /* NOT CHANGED */

    // Sometimes used on top of primary, for example in the divider between the calendar and event cards. Sorry :(
    // (and on buttons in the login page)
    // onSecondary: Colors.white

    // onError: Colors.white

    // onSurface: some gray color. Used for icons on search bars

    // onBackground: 

    // shadow: Colors.black, // Likely unused

    /* OLD COLORS */
    //surface: Color.fromRGBO(246, 243, 254, 1), // I guessed this color, it's close but not exactly the same as the old one
    //background: const Color.fromRGBO(241, 241, 241, 1), // Main old background color
  ),

  // Color used for circular loading indicator in some places
  // Also used in the background shape, and in many other places where previous
  // developers used orange to spice things up. Don't blame me if it looks bad.
  primaryColor: const Color.fromRGBO(245, 124, 0, 1), // colors.orange[700]
  primaryColorLight: const Color.fromRGBO(251, 140, 0, 1), //Colors.orange[600] // Used for the banner/background on the contact page

  appBarTheme: AppBarTheme(
    color: Colors.orange[700]
  ), // Top bar color
  bottomAppBarTheme: BottomAppBarTheme(color: Colors.orange[800]), // Bottom bar color

  textTheme: TextTheme(
    displayMedium: const TextStyle( // Used for the text on the loading widget
      fontSize: 30,
      fontWeight: FontWeight.normal,
      fontFamily: 'Helvetica Neue'
    ),
    titleLarge: const TextStyle( // Ex: all titles on top bar, titles of gallery albums
      fontSize: 22,
      fontStyle: FontStyle.normal,
      fontFamily: 'Helvetica Neue'
    ),
    headlineMedium: const TextStyle( // Ex: titles on the event page and songs
      fontSize: 25,
      fontStyle: FontStyle.normal,
      fontFamily: 'Helvetica Neue',
      color: const Color.fromRGBO(251, 140, 0, 1), // colors.orange[600]
    ),
    bodyMedium: const TextStyle(
      fontSize: 15,
      fontStyle: FontStyle.normal,
      fontFamily: 'Helvetica Neue'
    ),
    displaySmall: const TextStyle(
      fontSize: 12,
      fontStyle: FontStyle.normal,
      fontFamily: 'Helvetica Neue'
    ),
    labelLarge: const TextStyle( // Ex: text on image saving snackbar
      fontSize: 16,
      fontWeight: FontWeight.bold,
      fontFamily: 'Helvetica Neue'
    ),
  ),

  textButtonTheme: TextButtonThemeData(
    style: ButtonStyle(
      backgroundColor: MaterialStateProperty.all<Color>(Colors.orange[700]!),
      foregroundColor: MaterialStateProperty.all<Color>(Colors.white),
    ),
  ),

  checkboxTheme: CheckboxThemeData(
    fillColor: MaterialStateProperty.all<Color>(Colors.orange[800]!),
    checkColor: MaterialStateProperty.all<Color>(Colors.white),
  ),

  // Used for log in page (among other places?)
  inputDecorationTheme: InputDecorationTheme(
    focusedBorder: UnderlineInputBorder(borderSide: BorderSide(color: Colors.orange[600]!)),
    labelStyle: TextStyle(color: Colors.grey[600]!),
    hintStyle: TextStyle(color: Colors.grey[600]),
    floatingLabelStyle: TextStyle(color: Colors.orange[600]!),
    iconColor: Colors.grey[600],
  ),
);